### ISSUE TITLE
Streamdeck-elite disappears after restarting Stream Deck

### ISSUE THREAD

**Issue by Meridianstream** [mhwlng/streamdeck-elite#9] opened 2020-06-02 10:47 UTC
Followed instructions to setup Automatic Profile Switching in v. 2.0.2, on restarting Stream Deck after modding manifest.json and deleting profiles, Streamdeck-elite is no longer loaded. There is no option to install profiles therefore.

**Comment by Meridianstream** [comment] 2020-06-02 11:32
Further, if I undo changes to Manifest.json, then restart Stream Deck then plugin reappears.

**Comment by mhwlng** [comment] 2020-06-02 14:49
what do you mean no longer loaded ?
don't you see the list of buttons on the right anymore ?
![image](https://user-images.githubusercontent.com/1388886/83534242-e2a82c80-a4f0-11ea-9d1c-29bbddee0782.png)

can you see something in the log file ?
%appdata%\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin

Are you sure that you modded the manifest.json correctly?
is it valid json ? (comma's , braces, quotes etc.)
did you set up the device type correctly ?
can you post it here?

Every profile that you set up, does it contain at least one button from the plugin ?

**Comment by Meridianstream** [comment] 2020-06-02 16:21
[manifest.txt](https://github.com/mhwlng/streamdeck-elite/files/4718406/manifest.txt)

Loving the program btw. Just struggling with this.

I don't see the buttons as in your image.  Device type set correctly to 2 i.e. XL. I believe the syntax is correct though easy enough to make an error.
The profiles where setup as blank profiles or with standard Stream Deck default button.

**Comment by Meridianstream** [comment] 2020-06-02 16:23
Also just to be sure. When the guide states to delete the profiles it means from Stream Deck interface and not from new location they where exported to?

**Comment by mhwlng** [comment] 2020-06-02 16:25
yes, don't delete the .streamdeckprofile files.

The reason why it doesn't work, is that you forgot a quote after Name :

so	"Name":  not 	"Name:

p.s. You can use a tool like this, to validate the json : https://jsonlint.com/

Are you really going to make different profiles for EVERY state change ?
 (because you added all of them to the manifest) ?

**Comment by Meridianstream** [comment] 2020-06-02 16:49
Thank you.
No I just thought I would get the profiles in place as I add hotkeys etc .... but you are correct of course, it is massively overkill! I will try again later.

**Comment by mhwlng** [comment] 2020-06-02 16:53
The problem is, that if you add all placeholder profiles now. then they will be installed as read-only profiles. So, you won't be able to edit them. it's better to finish creating the profiles first and only then add selected ones to your manifest file.

**Closed as completed by mhwlng** 2020-06-02 16:53 UTC

**Comment by Meridianstream** [comment] 2020-06-02 16:54
ah ok. Thank you.
